language: node_js
node_js:
  - "node"
services:
  - postgresql
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - karma start
  - createdb glasshouse
  - createdb glasshouse_test
  - yarn test
